### ISSUE TITLE
Magic number checking code in loader.py seems wrong

### ISSUE THREAD

**Issue by eliben** [dabeaz/bitey#3]
In _check_magic you have:

`magic = open(filename,"rb").read(4)`

And then:

`elif magic == b'\x42\x43':``

It seems wrong to me. magic is 4 bytes long! You maybe meant:

`elif magic[:2] == b'\x42\x43` ?

Without this change bitey examples don't run

**Comment by dabeaz** [comment]
I just pushed a fixed this in Github.

Cheers,
Dave

**Comment by dabeaz** [comment]
Already pushed a fix (about 15 minutes ago) for this.
